#tomcat port
server:
  port: 9003
spring:
  devtools:
    livereload:
      enable: true

  #mysql
  datasource:
    dirver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?serverTimezone=Asia/Seoul
    username: root
    password: 1234

#mybatis
mybatis:
  type-aliase-package: data.mapper, data.dto
  mapper-locations:
  - /mapper/**/*.xml